---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    systemd: always
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    privileged: true
    systemd: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

  - name: rockylinux
    image: docker.io/rockylinux:9.3
    pre_build_image: true
    privileged: true
    systemd: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible
  playbook:
    converge: converge.yml

scenario:
  name: default
  test_sequence:
    - create
    - converge
