---
- name: Add Hashicrop repo to the source list
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp repo
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/{{  ansible_distribution_major_version }}/{{ ansible_architecture }}/stable"
    state: present
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true

- name: Install Nomad
  ansible.builtin.dnf:
    name: "nomad-{{ version }}"
    state: present
    update_cache: true
